app:
  pass_hash_cost: 5
  token_secret_key: "fb3299df-48c6-4fa3-9a72-b80f2a5a79f6"
  token_expires: "15m"

logger:
  level: 'debug'
  type: 'development'

postgres:
  url: 'host=localhost port=5432 user=postgres password=1 dbname=go_diploma sslmode=disable'

http:
  address: 'localhost:8080'

accrual_http:
  address: 'localhost:8081'